# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lhernand <lhernand@student.42.us.or>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/03/24 16:14:27 by lhernand          #+#    #+#              #
#    Updated: 2018/03/24 17:33:55 by lhernand         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#
# From an alpine image you’ll add to your container your favorite text editor, 
# vim or emacs, that will launch along with your container.
#

FROM debian:stable
RUN apt-get update && apt-get install -y vim

